/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => InlineOutlinePlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");

// src/settings.ts
var DEFAULT_SETTINGS = {
  showOutline: true,
  minimalOutline: false,
  hideProperties: true,
  hideScrollbar: false
};

// src/main.ts
var OUTLINE_STYLES = `
.inline-outline{position:fixed;right:24px;top:50%;transform:translateY(-50%);z-index:10;display:flex;flex-direction:column;align-items:flex-end;gap:6px;padding:12px 8px;border-radius:6px;background:transparent;max-height:70vh;overflow-y:auto;overflow-x:hidden}
.inline-outline:hover{background:var(--background-primary);box-shadow:0 2px 12px rgba(0,0,0,.1);padding:12px 16px 12px 12px;align-items:flex-start}
.inline-outline-item{display:flex;align-items:center;justify-content:flex-end;cursor:pointer;padding:3px 0;width:100%}
.inline-outline:hover .inline-outline-item{justify-content:flex-start}
.inline-outline-line{height:2px;border-radius:1px;background:var(--text-faint);opacity:.5;flex-shrink:0}
.inline-outline-item:hover .inline-outline-line{background:var(--text-accent);opacity:1}
.inline-outline-item.active .inline-outline-line{background:var(--text-accent);opacity:1;height:3px}
.inline-outline-level-1 .inline-outline-line{width:28px}
.inline-outline-level-2 .inline-outline-line{width:22px}
.inline-outline-level-3 .inline-outline-line{width:16px}
.inline-outline-level-4 .inline-outline-line{width:12px}
.inline-outline-level-5 .inline-outline-line{width:8px}
.inline-outline-level-6 .inline-outline-line{width:6px}
.inline-outline:hover .inline-outline-line{display:none}
.inline-outline-text{font-size:12px;line-height:1.4;color:var(--text-muted);white-space:nowrap;overflow:hidden;text-overflow:ellipsis;display:none;max-width:200px}
.inline-outline:hover .inline-outline-text{display:block}
.inline-outline-item:hover .inline-outline-text{color:var(--text-normal)}
.inline-outline-item.active .inline-outline-text{color:var(--text-accent);font-weight:500}
.inline-outline:hover .inline-outline-level-1{padding-left:0}
.inline-outline:hover .inline-outline-level-2{padding-left:10px}
.inline-outline:hover .inline-outline-level-3{padding-left:20px}
.inline-outline:hover .inline-outline-level-4{padding-left:30px}
.inline-outline:hover .inline-outline-level-5{padding-left:40px}
.inline-outline:hover .inline-outline-level-6{padding-left:50px}
.inline-outline-level-1 .inline-outline-text{font-weight:600;font-size:13px}
.inline-outline-level-2 .inline-outline-text{font-weight:500}
.inline-outline-empty{display:none}
.inline-outline:hover .inline-outline-empty{display:block;color:var(--text-faint);font-size:11px;white-space:nowrap}
.inline-outline::-webkit-scrollbar{width:4px}
.inline-outline::-webkit-scrollbar-track{background:transparent}
.inline-outline::-webkit-scrollbar-thumb{background:var(--background-modifier-border);border-radius:2px}
@media(max-width:900px){.inline-outline{display:none}}
.theme-dark .inline-outline:hover{background:var(--background-secondary);box-shadow:0 2px 16px rgba(0,0,0,.3)}
.inline-outline.minimal-style{top:120px;transform:none;gap:4px;padding:8px 6px;max-height:50vh}
.inline-outline.minimal-style:hover{padding:8px 12px 8px 8px}
.inline-outline.minimal-style .inline-outline-item{padding:2px 0}
.inline-outline.minimal-style .inline-outline-level-1 .inline-outline-line{width:20px}
.inline-outline.minimal-style .inline-outline-level-2 .inline-outline-line{width:16px}
.inline-outline.minimal-style .inline-outline-level-3 .inline-outline-line{width:12px}
.inline-outline.minimal-style .inline-outline-level-4 .inline-outline-line{width:9px}
.inline-outline.minimal-style .inline-outline-level-5 .inline-outline-line{width:6px}
.inline-outline.minimal-style .inline-outline-level-6 .inline-outline-line{width:4px}
.inline-outline.minimal-style .inline-outline-line{height:1.5px;opacity:.4}
.inline-outline.minimal-style .inline-outline-item.active .inline-outline-line{height:2px}
.inline-outline.minimal-style .inline-outline-text{font-size:11px;max-width:160px}
.inline-outline.minimal-style .inline-outline-level-1 .inline-outline-text{font-size:11px;font-weight:600}
.inline-outline.minimal-style .inline-outline-level-2 .inline-outline-text{font-weight:500}
.inline-outline.minimal-style:hover .inline-outline-level-1{padding-left:0}
.inline-outline.minimal-style:hover .inline-outline-level-2{padding-left:8px}
.inline-outline.minimal-style:hover .inline-outline-level-3{padding-left:16px}
.inline-outline.minimal-style:hover .inline-outline-level-4{padding-left:24px}
.inline-outline.minimal-style:hover .inline-outline-level-5{padding-left:32px}
.inline-outline.minimal-style:hover .inline-outline-level-6{padding-left:40px}
.inline-outline.minimal-style .inline-outline-empty{font-size:10px}
`;
var MINIMALIST_STYLES = `
/* Hide properties/frontmatter from main editor */
body.minimalist-hide-properties .markdown-source-view .metadata-container,
body.minimalist-hide-properties .markdown-preview-view .metadata-container {
	display: none !important;
}
/* Also hide raw YAML frontmatter in source mode */
body.minimalist-hide-properties .cm-line.HyperMD-frontmatter,
body.minimalist-hide-properties .cm-line.HyperMD-frontmatter-begin,
body.minimalist-hide-properties .cm-line.HyperMD-frontmatter-end {
	display: none !important;
}
/* Keep properties visible in sidebar */
body.minimalist-hide-properties .workspace-leaf-content[data-type="file-properties"] .metadata-container {
	display: block !important;
}
/* Style properties in sidebar */
body.minimalist-hide-properties .workspace-leaf-content[data-type="file-properties"] .metadata-properties-heading {
	font-size: 14px;
	color: var(--text-muted);
	font-weight: 500;
	padding: 8px 0;
}
body.minimalist-hide-properties .workspace-leaf-content[data-type="file-properties"] .collapse-indicator {
	display: none !important;
}
body.minimalist-hide-properties .workspace-leaf-content[data-type="file-properties"] .metadata-property {
	padding: 6px 0;
}
body.minimalist-hide-properties .workspace-leaf-content[data-type="file-properties"] .metadata-property-key {
	font-size: 12px;
	color: var(--text-muted);
	font-weight: 500;
}
body.minimalist-hide-properties .workspace-leaf-content[data-type="file-properties"] .metadata-property-value {
	font-size: 14px;
	color: var(--text-normal);
}

/* Hide scrollbar */
body.minimalist-hide-scrollbar .markdown-source-view ::-webkit-scrollbar,
body.minimalist-hide-scrollbar .markdown-preview-view ::-webkit-scrollbar {
	width: 0 !important;
	height: 0 !important;
}
body.minimalist-hide-scrollbar .cm-scroller {
	scrollbar-width: none;
}
`;
var READING_LINE_OFFSET = 60;
var LINK_REGEX = /\[\[(?:[^\]|]+\|)?([^\]]+)\]\]|\[([^\]]+)\]\([^)]+\)/g;
var InlineOutlinePlugin = class extends import_obsidian.Plugin {
  constructor() {
    super(...arguments);
    this.outlineEl = null;
    this.activeIndex = -1;
    this.headings = [];
    this.headingTexts = [];
    // Cached normalized texts
    this.scrollContainer = null;
    this.isReading = false;
    this.scrollRAF = null;
    this.resizeRAF = null;
    this.onScroll = () => {
      if (this.scrollRAF)
        return;
      this.scrollRAF = requestAnimationFrame(() => {
        this.scrollRAF = null;
        this.updateActive();
      });
    };
  }
  async onload() {
    await this.loadSettings();
    const outlineStyle = document.createElement("style");
    outlineStyle.id = "minimalist-outline-styles";
    outlineStyle.textContent = OUTLINE_STYLES;
    document.head.appendChild(outlineStyle);
    this.register(() => outlineStyle.remove());
    const minimalistStyle = document.createElement("style");
    minimalistStyle.id = "minimalist-editor-styles";
    minimalistStyle.textContent = MINIMALIST_STYLES;
    document.head.appendChild(minimalistStyle);
    this.register(() => minimalistStyle.remove());
    this.applyBodyClasses();
    this.addSettingTab(new MinimalistSettingTab(this.app, this));
    this.addCommand({ id: "toggle-outline", name: "Toggle Inline Outline", callback: () => this.toggle() });
    const refresh = (0, import_obsidian.debounce)(() => this.refresh(), 300, true);
    this.registerEvent(this.app.workspace.on("active-leaf-change", () => setTimeout(() => this.init(), 100)));
    this.registerEvent(this.app.workspace.on("layout-change", () => {
      this.updatePosition();
      setTimeout(() => this.init(), 100);
    }));
    this.registerEvent(this.app.metadataCache.on("changed", refresh));
    this.app.workspace.onLayoutReady(() => {
      this.createOutline();
      this.observeSidebar();
      setTimeout(() => this.init(), 100);
    });
  }
  onunload() {
    var _a, _b;
    (_a = this.scrollContainer) == null ? void 0 : _a.removeEventListener("scroll", this.onScroll);
    (_b = this.outlineEl) == null ? void 0 : _b.remove();
    if (this.scrollRAF)
      cancelAnimationFrame(this.scrollRAF);
    if (this.resizeRAF)
      cancelAnimationFrame(this.resizeRAF);
    document.body.classList.remove("minimalist-hide-properties", "minimalist-hide-scrollbar");
  }
  init() {
    this.setupScroll();
    this.refresh();
  }
  toggle() {
    if (this.outlineEl) {
      this.outlineEl.style.display = this.outlineEl.style.display === "none" ? "" : "none";
    }
  }
  createOutline() {
    var _a;
    (_a = this.outlineEl) == null ? void 0 : _a.remove();
    if (!this.settings.showOutline)
      return;
    this.outlineEl = document.createElement("div");
    this.outlineEl.className = "inline-outline" + (this.settings.minimalOutline ? " minimal-style" : "");
    this.outlineEl.id = "inline-outline";
    document.body.appendChild(this.outlineEl);
  }
  applyBodyClasses() {
    document.body.classList.toggle("minimalist-hide-properties", this.settings.hideProperties);
    document.body.classList.toggle("minimalist-hide-scrollbar", this.settings.hideScrollbar);
  }
  updateOutlineStyle() {
    var _a;
    (_a = this.outlineEl) == null ? void 0 : _a.classList.toggle("minimal-style", this.settings.minimalOutline);
  }
  toggleOutlineVisibility() {
    var _a;
    if (this.settings.showOutline) {
      if (!this.outlineEl) {
        this.createOutline();
        this.refresh();
      }
    } else {
      (_a = this.outlineEl) == null ? void 0 : _a.remove();
      this.outlineEl = null;
    }
  }
  setupScroll() {
    var _a, _b;
    (_a = this.scrollContainer) == null ? void 0 : _a.removeEventListener("scroll", this.onScroll);
    const view = this.app.workspace.getActiveViewOfType(import_obsidian.MarkdownView);
    if (!view) {
      this.scrollContainer = null;
      return;
    }
    this.isReading = view.getMode() === "preview";
    const selector = this.isReading ? ".markdown-preview-view" : ".cm-scroller";
    this.scrollContainer = view.contentEl.querySelector(selector);
    (_b = this.scrollContainer) == null ? void 0 : _b.addEventListener("scroll", this.onScroll, { passive: true });
  }
  observeSidebar() {
    const sidebar = document.querySelector(".mod-right-split");
    if (!sidebar)
      return;
    new ResizeObserver(() => {
      if (this.resizeRAF)
        return;
      this.resizeRAF = requestAnimationFrame(() => {
        this.resizeRAF = null;
        this.updatePosition();
      });
    }).observe(sidebar);
  }
  updatePosition() {
    if (!this.outlineEl)
      return;
    const sidebar = document.querySelector(".mod-right-split");
    const width = (sidebar == null ? void 0 : sidebar.getBoundingClientRect().width) || 0;
    this.outlineEl.style.right = `${width > 0 ? width + 24 : 24}px`;
  }
  refresh() {
    var _a;
    const file = this.app.workspace.getActiveFile();
    const cache = file && this.app.metadataCache.getFileCache(file);
    this.headings = ((_a = cache == null ? void 0 : cache.headings) == null ? void 0 : _a.map((h) => ({
      level: h.level,
      text: h.heading,
      position: h.position
    }))) || [];
    this.headingTexts = this.headings.map((h) => this.strip(h.text).toLowerCase());
    this.render();
    this.activeIndex = -1;
    if (this.isReading) {
      setTimeout(() => this.updateActive(), 150);
    } else {
      this.updateActive();
    }
  }
  strip(text) {
    return text.replace(LINK_REGEX, "$1$2").trim();
  }
  render() {
    if (!this.outlineEl)
      return;
    this.outlineEl.innerHTML = "";
    if (!this.headings.length) {
      const empty = document.createElement("div");
      empty.className = "inline-outline-empty";
      empty.textContent = "No headings";
      this.outlineEl.appendChild(empty);
      return;
    }
    const frag = document.createDocumentFragment();
    this.headings.forEach((h, i) => {
      const item = document.createElement("div");
      item.className = `inline-outline-item inline-outline-level-${h.level}`;
      item.innerHTML = `<div class="inline-outline-line"></div><span class="inline-outline-text">${this.strip(h.text)}</span>`;
      item.onclick = () => this.navigate(i);
      frag.appendChild(item);
    });
    this.outlineEl.appendChild(frag);
  }
  updateActive() {
    var _a;
    if (!this.outlineEl || !this.headings.length || !this.scrollContainer)
      return;
    const rect = this.scrollContainer.getBoundingClientRect();
    const readingLine = rect.top + READING_LINE_OFFSET + 20;
    let active = 0;
    if (this.isReading) {
      const view = this.app.workspace.getActiveViewOfType(import_obsidian.MarkdownView);
      const preview = view == null ? void 0 : view.contentEl.querySelector(".markdown-preview-view");
      if (!preview)
        return;
      const els = Array.from(preview.querySelectorAll("h1,h2,h3,h4,h5,h6"));
      let lastAbove = 0;
      for (const el of els) {
        const top = el.getBoundingClientRect().top;
        const text = (el.textContent || "").toLowerCase().trim();
        let idx = this.headingTexts.indexOf(text);
        if (idx === -1) {
          idx = this.headingTexts.findIndex((t) => text.includes(t) || t.includes(text));
        }
        if (idx === -1)
          continue;
        if (top <= readingLine)
          lastAbove = idx;
        if (top >= readingLine - 20) {
          active = idx;
          break;
        }
      }
      if (active === 0 && lastAbove > 0)
        active = lastAbove;
    } else {
      const view = this.app.workspace.getActiveViewOfType(import_obsidian.MarkdownView);
      const cm = (_a = view == null ? void 0 : view.editor) == null ? void 0 : _a.cm;
      if (!(cm == null ? void 0 : cm.coordsAtPos))
        return;
      let lastAbove = 0;
      for (let i = 0; i < this.headings.length; i++) {
        try {
          const line = this.headings[i].position.start.line;
          const coords = cm.coordsAtPos(cm.state.doc.line(line + 1).from, -1);
          if (!coords)
            continue;
          if (coords.top <= readingLine)
            lastAbove = i;
          if (coords.top >= readingLine - 20) {
            active = i;
            break;
          }
        } catch (e) {
          continue;
        }
      }
      if (active === 0 && lastAbove > 0)
        active = lastAbove;
    }
    if (active !== this.activeIndex) {
      this.activeIndex = active;
      const items = this.outlineEl.querySelectorAll(".inline-outline-item");
      items.forEach((el, i) => el.classList.toggle("active", i === active));
    }
  }
  navigate(index) {
    var _a;
    const h = this.headings[index];
    if (!h)
      return;
    const view = this.app.workspace.getActiveViewOfType(import_obsidian.MarkdownView);
    if (!view)
      return;
    this.activeIndex = index;
    (_a = this.outlineEl) == null ? void 0 : _a.querySelectorAll(".inline-outline-item").forEach(
      (el, i) => el.classList.toggle("active", i === index)
    );
    const file = this.app.workspace.getActiveFile();
    if (file) {
      this.app.workspace.openLinkText(
        file.path + "#" + h.text,
        file.path,
        false
      );
    }
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
};
var MinimalistSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    this.containerEl.empty();
    this.containerEl.createEl("h2", { text: "The Minimalist Editor" });
    this.containerEl.createEl("h3", { text: "Inline Outline" });
    new import_obsidian.Setting(this.containerEl).setName("Show Outline").setDesc("Display the inline outline on the right side of the editor").addToggle((t) => t.setValue(this.plugin.settings.showOutline).onChange(async (v) => {
      this.plugin.settings.showOutline = v;
      await this.plugin.saveSettings();
      this.plugin.toggleOutlineVisibility();
    }));
    new import_obsidian.Setting(this.containerEl).setName("Minimal Style").setDesc("Notion-like: positioned higher, smaller lines and text").addToggle((t) => t.setValue(this.plugin.settings.minimalOutline).onChange(async (v) => {
      this.plugin.settings.minimalOutline = v;
      await this.plugin.saveSettings();
      this.plugin.updateOutlineStyle();
    }));
    this.containerEl.createEl("h3", { text: "Distraction-free" });
    new import_obsidian.Setting(this.containerEl).setName("Hide Properties").setDesc("Hide the properties/metadata panel from the editor (still visible in sidebar)").addToggle((t) => t.setValue(this.plugin.settings.hideProperties).onChange(async (v) => {
      this.plugin.settings.hideProperties = v;
      await this.plugin.saveSettings();
      this.plugin.applyBodyClasses();
    }));
    new import_obsidian.Setting(this.containerEl).setName("Hide Scrollbar").setDesc("Hide the scrollbar for a cleaner appearance").addToggle((t) => t.setValue(this.plugin.settings.hideScrollbar).onChange(async (v) => {
      this.plugin.settings.hideScrollbar = v;
      await this.plugin.saveSettings();
      this.plugin.applyBodyClasses();
    }));
  }
};
